name: Build
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
    - id: checkout
      name: Check out source code
      uses: actions/checkout@v2
    
    - id: cache-seek
      name: Check for yarn cache hit
      uses: c-hive/gha-yarn-cache@v1

    - id: install
      name: Install dependencies
      run: |-
        yarn install --frozen-lockfile

    - id: test
      name: Run unit tests
      run: |-
        npm test
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2

      - id: ref
        name: Replace / to - in ref name for docker tag.
        run: |-
          TAG_REF=$(echo $GITHUB_REF | sed 's/\//-/g')
          echo "::set-output name=tag-ref::$TAG_REF"

      - id: build
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ format('{0}:{1},{0}:{2}', github.repository, steps.ref.outputs.tag-ref, github.sha) }}