name: Build
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
    - id: checkout
      name: Check out source code
      uses: actions/checkout@v2
    
    - id: cache-seek
      name: Check for yarn cache hit
      uses: c-hive/gha-yarn-cache@v1

    - id: install
      name: Install dependencies
      if: steps.cache-seek.outputs.cache-hit == false
      run: |-
        yarn install --frozen-lockfile

    - id: test
      name: Run unit tests
      run: |-
        npm test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2

      - id: build
        name: Build Docker image
        run: |-
          docker